services:
  db:
    ports:
    # Export port for debug only. The DB should be accessible only inside the docker network
    - 127.0.0.1:${POSTGRES_PORT:-5432}:5432
  redis:
    ports:
    - 127.0.0.1:${REDIS_PORT:-6379}:6379
