services:
  db:
    image: vue_ensemble/postgres-vector:latest
    build:
      dockerfile: Dockerfile.postgres
    pull_policy: never
    # user: postgres
    shm_size: 16g
    container_name: vue_ensemble_pg
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config-file=/etc/postgresql/postgresql.conf"]
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  redis:
    image: redis:8.2
    container_name: vue_ensemble_redis
