"""empty message

Revision ID: 2ac3de316280
Revises: cc4904cba45f
Create Date: 2025-11-15 08:39:21.753455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2ac3de316280'
down_revision: Union[str, Sequence[str], None] = 'cc4904cba45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i_people_present_csv', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('i_people_absent_given_power_csv', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('i_people_absent_csv', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('i_secretaries_csv', sa.TEXT(), nullable=True))
        batch_op.drop_column('i_secretaries_tsv')
        batch_op.drop_column('i_people_present_tsv')
        batch_op.drop_column('i_people_absent_tsv')
        batch_op.drop_column('i_people_absent_given_power_tsv')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i_people_absent_given_power_tsv', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('i_people_absent_tsv', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('i_people_present_tsv', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('i_secretaries_tsv', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('i_secretaries_csv')
        batch_op.drop_column('i_people_absent_csv')
        batch_op.drop_column('i_people_absent_given_power_csv')
        batch_op.drop_column('i_people_present_csv')

    # ### end Alembic commands ###
