"""empty message

Revision ID: 38b24c5efd07
Revises: 2ac3de316280
Create Date: 2025-11-15 08:40:45.402410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "38b24c5efd07"
down_revision: Union[str, Sequence[str], None] = "2ac3de316280"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_column("events_processing_details")
        batch_op.drop_column("ocr_processing_details")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ocr_processing_details",
                postgresql.JSONB(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "events_processing_details",
                postgresql.JSONB(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
