"""empty message

Revision ID: cc4904cba45f
Revises: 27f4335c65f0
Create Date: 2025-11-13 22:54:53.295476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "cc4904cba45f"
down_revision: Union[str, Sequence[str], None] = "27f4335c65f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("locality_id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.TEXT(), nullable=True),
        sa.Column("file_extension", sa.TEXT(), nullable=True),
        sa.Column("source_url", sa.TEXT(), nullable=True),
        sa.Column("base_url", sa.TEXT(), nullable=True),
        sa.Column("raw_content", sa.LargeBinary(), nullable=True),
        sa.Column("gzipped", sa.Boolean(), nullable=True),
        sa.Column("i_type", sa.TEXT(), nullable=True),
        sa.Column("i_topic", sa.TEXT(), nullable=True),
        sa.Column("i_title", sa.TEXT(), nullable=True),
        sa.Column("i_summary", sa.TEXT(), nullable=True),
        sa.Column(
            "i_md_from_ocr", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("i_year", sa.Integer(), nullable=True),
        sa.Column("i_month", sa.Integer(), nullable=True),
        sa.Column("i_day_number", sa.Integer(), nullable=True),
        sa.Column("i_hour", sa.Integer(), nullable=True),
        sa.Column("i_minute", sa.Integer(), nullable=True),
        sa.Column("i_people_present_tsv", sa.TEXT(), nullable=True),
        sa.Column("i_people_absent_given_power_tsv", sa.TEXT(), nullable=True),
        sa.Column("i_people_absent_tsv", sa.TEXT(), nullable=True),
        sa.Column("i_secretaries_tsv", sa.TEXT(), nullable=True),
        sa.Column(
            "ocr_processing_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "events_processing_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["locality_id"],
            ["locality.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documentedevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("i_topic", sa.TEXT(), nullable=True),
        sa.Column("i_summary", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("locality", schema=None) as batch_op:
        batch_op.add_column(sa.Column("type", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("postcode", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("country_iso3", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("website", sa.TEXT(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "administrative_reporting_setup",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=True,
            )
        )
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("locality", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("administrative_reporting_setup")
        batch_op.drop_column("website")
        batch_op.drop_column("country_iso3")
        batch_op.drop_column("postcode")
        batch_op.drop_column("type")

    op.drop_table("documentedevent")
    op.drop_table("document")
    # ### end Alembic commands ###
